# Generated by Django 2.2 on 2019-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_text', models.CharField(max_length=500)),
                ('capture_date', models.DateTimeField(verbose_name='date captured')),
            ],
        ),
    ]
