# Generated by Django 2.2 on 2019-04-29 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='category',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='status',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
