# Generated by Django 2.2 on 2019-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_capture_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='group',
        ),
        migrations.AddField(
            model_name='capture',
            name='project',
            field=models.CharField(default='', max_length=500),
        ),
    ]
