# Generated by Django 2.2 on 2019-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0005_capture_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='category',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capture',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
