# Generated by Django 2.2 on 2019-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_auto_20190501_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='due_date',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
