# Generated by Django 2.2 on 2019-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0007_capture_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
