# Generated by Django 2.2 on 2019-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0008_auto_20190506_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='project',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
