# Generated by Django 2.2 on 2019-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0010_auto_20190506_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='any_time',
            field=models.SmallIntegerField(default=0),
        ),
    ]
